# Generated by Django 3.2.5 on 2021-07-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'flat']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['checkin']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('flat', 'city')},
        ),
    ]
