# Generated by Django 3.2.5 on 2021-07-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='income',
            field=models.FloatField(),
        ),
    ]
